volumes:
  intel-gpu-data:
  intel-gpu-grafana:

services:
  monitor:
    build: .
    command: ["stream"]
    # required for gpu access
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app

  questdb:
    image: questdb/questdb
    restart: always
    ports:
      - "13512:8812"
    volumes:
      - intel-gpu-data:/root/.questdb/db

  grafana:
    image: grafana/grafana
    restart: always
    depends_on:
      - questdb
    ports:
      - "13511:3000"
    volumes:
      - intel-gpu-grafana:/var/lib/grafana
      - ./grafana/:/etc/grafana/provisioning/