{
 "title": "Intel Gpu Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Engine Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\",\r\nrender_3d_engine_utilization_pct as 'Render/3D',\r\nblitter_engine_utilization_pct as 'Blitter',\r\ncompute_engine_utilization_pct as 'Compute',\r\nvideo_engine_utilization_pct as 'Video',\r\nvideo_enhance_engine_utilization_pct as 'VideoEnhance',\r\n 'GPU ' || deviceid::int || ': ' as device\r\n from gpu_metrics order by device"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", gpu_memory_used_mib as \" \", 'GPU ' || deviceid::int as device from gpu_metrics order by device"
    }
   ]
  },
  {
   "title": "Power Usage Watts",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", gpu_power_w as \" \", 'GPU ' || deviceid::int as device from gpu_metrics order by device"
    }
   ]
  },
  {
   "title": "GPU Frequency",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", gpu_power_w as \" \", 'GPU ' || deviceid::int as device from gpu_metrics order by device"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", gpu_memory_utilization_pct as \" \", 'GPU ' || deviceid::int as device from gpu_metrics order by device"
    }
   ]
  },
  {
   "title": "Max Engine Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS \"time\",\r\n  'GPU ' || deviceid::int as device,\r\n  greatest(\r\n    render_3d_engine_utilization_pct::int,\r\n    blitter_engine_utilization_pct::int,\r\n    compute_engine_utilization_pct::int,\r\n    video_engine_utilization_pct::int,\r\n    video_enhance_engine_utilization_pct::int\r\n  ) as ' '\r\n  \r\nfrom gpu_metrics\r\norder by device"
    }
   ]
  }
 ]
}